import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

export const config = {
  unstable_runtimeJS: false,
};

const Home: NextPage = () => {
  function clickMe() {
    console.log("clicked", new Date().toString());
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to asdf</h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
        <button onClick={clickMe}>Console.log('clicked')</button>
      </main>
    </div>
  );
};

export default Home;
